name: Build Client Executable

on:
  push:
    branches: [main]
    paths:
      - 'client.py'

jobs:
  build-client:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Build client executable
        run: |
          pip install pyinstaller
          pyinstaller --noconsole --onefile --icon=icon.ico client.py || pyinstaller --noconsole --onefile client.py

      - name: Create executables directory
        run: |
          mkdir -p executables
        shell: bash

      - name: Move executable to executables folder (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          if not exist executables mkdir executables
          move dist\client.exe executables\client-windows.exe
        shell: cmd

      - name: Move executable to executables folder (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: |
          mv dist/client executables/client-linux
        shell: bash

      - name: Move executable to executables folder (macOS)
        if: matrix.os == 'macos-latest'
        run: |
          mv dist/client executables/client-macos
        shell: bash

      - name: Upload Executable Artifact
        uses: actions/upload-artifact@v4
        with:
          name: client-executable-${{ matrix.os }}
          path: executables/*

      - name: Commit and push executables to main branch
        if: github.ref == 'refs/heads/main'
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git fetch
          git checkout main
          git pull
          git add executables/*
